// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKrbEXguZu0gLJmq-KsU0-1UBnO8xfe4',
    appId: '1:364120111691:web:0a20738e90f95d569dabce',
    messagingSenderId: '364120111691',
    projectId: 'fjc2022-2e2ec',
    authDomain: 'fjc2022-2e2ec.firebaseapp.com',
    storageBucket: 'fjc2022-2e2ec.appspot.com',
    measurementId: 'G-R9HKWNJP4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5RNgsqXvDUEiKO2PhdUhVa8RMRKFL80',
    appId: '1:364120111691:android:539693632d2c89679dabce',
    messagingSenderId: '364120111691',
    projectId: 'fjc2022-2e2ec',
    storageBucket: 'fjc2022-2e2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZPS-L12L1_V9HNbcCDV6PKM_t-Px-fTk',
    appId: '1:364120111691:ios:61dc7e6b7e1aa2529dabce',
    messagingSenderId: '364120111691',
    projectId: 'fjc2022-2e2ec',
    storageBucket: 'fjc2022-2e2ec.appspot.com',
    iosClientId: '364120111691-mbnq4h5t89ssn1440co35r3m874s8enp.apps.googleusercontent.com',
    iosBundleId: 'com.example.fjc2022',
  );
}
